### ISSUE TITLE
Adjusting a joystick axis or pressing a button while playing causes the game to freeze

### ISSUE THREAD

**Issue by jimj316** [eevee/lexys-labyrinth#104]
\> be me
\> be on Debian 12 w/ Firefox 115.10.0esr (64-bit)
\> decide to play some LL
\> have a Mad Catz F.L.Y. 5 flight stick plugged in for no reason
\> brush against the throttle axis while reaching for Gamer Juice
\> game freezes completely, input doesn't work, everything's dead
\> try other levels, joystick axes and buttons
\> happens every time without fail
\> check the console hoping for answers
\> https://gist.github.com/jimj316/3c2256c475c0a72f3bb75ddbf8ca8897 repeated every frame

mfw

**Comment by eevee** [comment]
whoops!  hopefully fixed now
