### ISSUE TITLE
Lexy's Labyrinth runs ~95-98% of the speed of CC2

### ISSUE THREAD

**Issue by Patashu** [eevee/lexys-labyrinth#16]
Haven't made any attempt to investigate why, but consistently when recording the same replay in LL and CC2 I have to speed LL's footage up because it's slightly slower than CC2. Slowness might be inconsistent too. Might need a mechanic like 'if we're falling too far behind wall time speed up the next frame slightly'?

**Comment by eevee** [comment]
wild guess: could be because i schedule the next tic _after_ the current tic has run, so each tic is actually (0.05s + time it takes to run the tic) long

**Comment by eevee** [comment]
i think this is fixed now but lmk if now

**Comment by Patashu** [comment]
It looks like it's now a lot more consistent, but still slightly slower, so we're closer to parity!

I took some measurements for the three new videos I made. Lexy's Labyrinth runs at 98.1~98.3% speed of CC2 for all three of them - BLOCK BUSTER II, ANTARTICA and DA BOMB. (I haven't checked if this is because CC2 is slightly > 60 fps or LL is slightly < 60 fps.)

**Comment by eevee** [comment]
hmm.  bearing in mind that cc2 is a rather old game...  if it were running on a 17ms per frame timeout (rather than 16⅔ms), then every 60 frames would take 1.02s, and 1/1.02 is 98.04%?

i'd definitely be interested in knowing who's running closer to 20 tics per second, though if LL is running slow then i'm not totally sure what more i can do about it

**Comment by Patashu** [comment]
I just did a test with a stopwatch, and Lexy thinks 59 seconds/1180 tics passed in the span of 60 real time seconds. 59/60 is 98.4%, matching the observations from my video footage, so I'm pretty confident it's LL that's slow and CC2 that's on time.

My two fix suggestions would be:
1) Keep track of how much wall time has been spent on each turn, and if LL is slightly behind/slightly ahead speed up/slow down the next tic by a bit to get closer.
2) Just have a magic number equal to 0.982 in the code and multiply tic duration by that.
