### ISSUE TITLE
Turn based mode: Lexy waits a tic after making a move

### ISSUE THREAD

**Issue by Patashu** [eevee/lexys-labyrinth#17]
Tested on CCLP1 - Key Pyramid in debug mode at 4x slower. The first move takes 4 tics - every move thereafter skips a tic instantly (e.g. it goes from 4 to 6 then counts 7, 8, 9, 10 then waits for your next input). If you record it as a replay and watch it back, you see Lexy wait a tic after each move like she's stutter stepping. Tapping spacebar also advances 2 tics instead of 1, unless you tap it fast enough that the previous tic hasn't finished.

**Comment by magical** [comment]
Ah, that would explain why the timing in Avalanche seemed to be off when I played it in turn based mode.
