### ISSUE TITLE
Patterned walls and patterned floors don't contrast each other enough

### ISSUE THREAD

**Issue by ncrecc** [eevee/lexys-labyrinth#19]
The green patterned walls/floors are fine, but the other wall/floor pairs use very similar coloration in a way that doesn't really cement their roles as solid and unsolid.
Top: patterned walls/floors as they actually appear, bottom: patterned walls/floors after mucking around with floor brightness (without regards to palette)
![image](https://user-images.githubusercontent.com/11216597/103298265-f3a61700-49c7-11eb-9959-cece2d7ce5bd.png)

**Comment by eevee** [comment]
100% correct, so here you go:

![image](https://user-images.githubusercontent.com/94112/103307616-c0668680-49cd-11eb-8ee8-b1650333519f.png)

I try to batch commits to the tileset (to reduce git churn since it can't store diffs), but it'll show up live shortly.
