### ISSUE TITLE
, and . to cycle between variants of a tile doesn't work with letter tile

### ISSUE THREAD

**Issue by ncrecc** [eevee/lexys-labyrinth#21]
If the precedent were that ,. is only for when the variants of a tile are *rotations*, that would be inconsistent with the logic counter tile (whose number is selected with ,. and has no manual selection menu like letter tiles and tracks)

**Comment by eevee** [comment]
yeah okay i'll buy it

**Comment by eevee** [comment]
ASCII and arrows are in separate cycles since I don't think there's a sensible place to chain them together

also I _do_ want the counter tile to have a selection menu, just haven't gotten to it yet  :)
