### ISSUE TITLE
Pressing Space takes me to the bitbusters wiki page on Chip's Challenge Level Pack 3 

### ISSUE THREAD

**Issue by ncrecc** [eevee/lexys-labyrinth#24]
Yep, this is a weird one. This always happens on LL except when the game frame is currently active (and not paused or on the "whoops" screen).
Only lead is so far this is only happening on Vivaldi (3.5.2115.73), where Space simulates a mouse click on non-text field elements focused via Tab (though, on LL, pressing space takes me to the CCLP3 wiki page even when I already *do* have something focused). Could this be due to some unused "more info" button that links to CCLP3 by default, that Vivaldi automatically focuses on for some arcane reason?
(Space to click currently focused element is, of course, the one thing it doesn't let me change. Slow clap for Vivaldi.)

**Comment by eevee** [comment]
Apparently this is because Vivaldi treats spacebar as a shortcut for "next page", though I don't know how it intuits what the next page is.

Is this still happening?  I thought I fixed it with a well-placed `preventDefault` a couple days ago.

**Comment by ncrecc** [comment]
Still happening, yep.

**Comment by eevee** [comment]
Looks like Vivaldi's "fast forward" feature looks for links with particular names, and it's latching onto the "More" links at the ends of the CCLP descriptions.  I am _definitely_ calling `preventDefault()`, and I don't know why that isn't working, but an incredibly dumb workaround is to...  change the text of those links.  Tried that with commit 5653fc9, hopefully it helps!

**Comment by ncrecc** [comment]
That resolves it for now, thanks!
