### ISSUE TITLE
Inactive transmogrifiers still animate

### ISSUE THREAD

**Issue by ncrecc** [eevee/lexys-labyrinth#28]
![mogrif](https://user-images.githubusercontent.com/11216597/104820713-c6999700-5804-11eb-979c-cb79ecfb6cdc.gif)
This is not quite what happens in CC2. In CC2, inactive transmogrifiers only animate if there are no wires explicitly on their tile:
![mogrif2](https://user-images.githubusercontent.com/11216597/104820748-082a4200-5805-11eb-95a0-1440ec451be7.gif)
(The second transmogrifier in the above gif does not have a wire on its tile, because it was placed on top of a pre-existing wire and overwrote it. It still acts as an inactive transmogrifier because there's a wire leading up to it.)

**Comment by eevee** [comment]
Same problem exists for red teleporters.  (Won't be replicating the exact CC2 behavior, as that seems to be a bug due to transmogrifiers originally being wired in-cell like teleporters and later being changed to wired on edge like switch doors.)
