### ISSUE TITLE
Cerise's editor description refers to her as a "rabbat" - typo?

### ISSUE THREAD

**Issue by ncrecc** [eevee/lexys-labyrinth#39]
I figured "rabbat" might refer to a different species than "rabbit" since she has 4 ears, but the tile that blocks her is just named "no bunnies sign" so I'm not sure

**Comment by eevee** [comment]
Yeah, the species is "singing rabbat", or I guess actually she's a gelbeast imprinted on a singing rabbat, but that's rather wordy to put in the name of the sign, so  :)
