### ISSUE TITLE
Can pickup keys on rewind

### ISSUE THREAD

**Issue by orez-** [eevee/lexys-labyrinth#4]
On level 100 of level pack 1 (Loose Pocket) Lexy starts on a green key that she can't pick up, and is only able to move onto a force floor that pushes her away from the key. The point of the level is to find the suction boots that let her go back to pick up the key so she can exit the level. However after moving off of the key, if you rewind or undo Lexy back to the initial position she will pick up the key, bypassing much of the level. Instead, I would expect rewinding to move her back onto the key without picking it up.

This is a pretty minor issue! I can't imagine it affects a lot of levels. But I figured I'd at least mention it.

(Thank you for making Lexy's Labyrinth! I'm loving playing through it. I was a big fan of Chip's Challenge as a kid, but don't have the patience to play a version without a rewind feature these days.)

**Comment by eevee** [comment]
That was truly baffling until I found the cause, which even had a TODO telling me to fix it!  Didn't expect it to have actual gameplay impact though.

Thanks for reporting, and I'm glad you're enjoying it!
