### ISSUE TITLE
Lexy's downward pushing sprites aren't very clear

### ISSUE THREAD

**Issue by ncrecc** [eevee/lexys-labyrinth#40]
![pushinggggg](https://user-images.githubusercontent.com/11216597/106474973-714fbd80-6473-11eb-9a54-f36cfb340f23.gif)
Cerise is more evidently leaning over and putting her arms straight forward. Lexy looks like she's just walking with her hands below her breasts.

**Comment by eevee** [comment]
fixed in 20e67b4
