### ISSUE TITLE
Black buttons are too fast

### ISSUE THREAD

**Issue by ncrecc** [eevee/lexys-labyrinth#48]
When holding down from this position:
![image](https://user-images.githubusercontent.com/11216597/108932541-873a4380-7617-11eb-9ba4-9da459e24ceb.png)
In CC2, you briefly hit the top pink wall before you go through it. In LL (with cc2 strict compat), you just go straight through without hitting it.

**Comment by eevee** [comment]
i think this is what's desyncing CC2LP1 \#106 Cold Lazarus
