### ISSUE TITLE
Possible to walk through facade walls

### ISSUE THREAD

**Issue by swantzter** [eevee/lexys-labyrinth#5]
When you come into contact with a facade wall and it turns to a solid wall I think it should prevent you from moving onto the now-solid wall. Otherwise pack 1 level 5 is incredibly easy. Fantastic piece of work this in either case

![Screenshot_20201001-105651](https://user-images.githubusercontent.com/10356719/94789208-ebdcd380-03d4-11eb-98e3-a139f90f02a2.jpg)

**Comment by eevee** [comment]
lmao god dammit, this is a regression from a fix for something else.  thanks for pointing it out so quick, that would've been embarrassing

**Comment by swantzter** [comment]
Classic 😅 thanks for looking into it so fast
