### ISSUE TITLE
Game no longer loads on Vivaldi

### ISSUE THREAD

**Issue by ncrecc** [eevee/lexys-labyrinth#56]
Works fine on Firefox, Edge, and Chromium, but never loads on Vivaldi. The "Sorry, the game was unable to load" message never appears, either (but does display for a split-second when loading on Edge or Chromium)

**Comment by eevee** [comment]
hm, strongly suspecting patashu's use of `??` — very recent addition and vivaldi lags a ways behind

**Comment by Patashu** [comment]
ah, didn't know ?? would break on some browsers - apologies

**Comment by eevee** [comment]
wait, sorry, that can't be it; i've used it myself.  maybe `?.`?

**Comment by eevee** [comment]
_guessing_ that's it, but please reopen if i'm wrong!
