### ISSUE TITLE
Game freezes visually if you enter a turnstile from above or to the right

### ISSUE THREAD

**Issue by ncrecc** [eevee/lexys-labyrinth#58]
![turntable](https://user-images.githubusercontent.com/11216597/109577859-500add00-7ac4-11eb-8ce6-fb4141b57337.gif)

**Comment by ncrecc** [comment]
The level can still be played, but it never visually updates from its initial state

**Comment by Patashu** [comment]
looks like it's a consequence of the (not yet in github, but live on https://c.eev.ee/lexys-labyrinth/ ) change to turntables to make them call attempt_step after changing your turning direction: in tileset.js _draw_standard, p is barely negative and needs to be rounded up to 0. I'm not sure why calling attempt_step at this particular timing causes it, though.

**Comment by eevee** [comment]
my bad, i should've used `attempt_out_of_turn_step`
