### ISSUE TITLE
Halos don't work for monsters (given via gift bow)

### ISSUE THREAD

**Issue by ncrecc** [eevee/lexys-labyrinth#61]
The monsters will still die in tiles that would kill them and don't remove those tiles

**Comment by Patashu** [comment]
This would be cool, but I think I'll hold off on it since eevee has a halo revamp in mind and whether or not it will work for non-players remains to be seen

**Comment by eevee** [comment]
yeah i've replaced the halo with the ankh, which explicitly only saves players (via a different mechanism), so this no longer applies
