### ISSUE TITLE
Trap ejections under Lynx compat mode look choppy

### ISSUE THREAD

**Issue by ncrecc** [eevee/lexys-labyrinth#68]
![ejection](https://user-images.githubusercontent.com/11216597/111857141-ea14b700-8905-11eb-821a-53ad0c203c07.gif)

**Comment by eevee** [comment]
this is a quirk of how trap ejection works in lynx — anything standing on an open trap effectively takes an extra turn.  i could try to detect when that's happening and shorten the cooldown by a tic instead, so the object appears to be moving faster?  offhand i don't _think_ that would affect compat

**Comment by eevee** [comment]
actually i think there might have been a bug here that made the player even faster than intended (fixed by e8cb95a).  trying it now, you don't move nearly that fast, and you clearly animate the whole way through, so i think this is fine
