### ISSUE TITLE
"Fire doesn't block monsters" compat rule should exclude beetles

### ISSUE THREAD

**Issue by ncrecc** [eevee/lexys-labyrinth#69]
Nice if this were replicated: in MSCC, bugs (beetles) are the one monster which refuses to walk into fire

**Comment by hyzchip** [comment]
Bugs/beetles are not "the one monster" that avoid fire.  Walkers.

**Comment by eevee** [comment]
for clarity, that last comment wasn't an argument; _both_ bugs and walkers avoid fire in MS
