### ISSUE TITLE
somehow my score is NaN now

### ISSUE THREAD

**Issue by rpearl** [eevee/lexys-labyrinth#8]
sorry, this isn't a very actionable bug report, but when starting cclp3, somehow my initial score was set to NaN. And of course, NaN + n for any n is also NaN, so my score is stuck there! 

Here is a not-very-helpful screenshot of what happened after the first level of that pack: https://www.dropbox.com/s/hcsaxxjvbe99i64/Screen%20Shot%202020-10-21%20at%2010.37.16%20PM.png?dl=0

If I figure out how to repro, I'll reply. I'll probably just go set my score to something in JS if i can figure out the right incantation without too much effort.

**Comment by eevee** [comment]
Yeah whoops my bad; levels stopped being aware of their numbers when I changed a bunch of stuff about level loading, and that turned into NaNs.  I just fixed this a moment ago, and it should recompute your total score when you next load the pack.

**Comment by rpearl** [comment]
hooray! thanks for making this, I have a serious grid-based-puzzle-game addiction and it's nice to revisit old favorites
