### ISSUE TITLE
Cannot click on the chip's challenge level packs under "Just play something" section

### ISSUE THREAD

**Issue by Benjins** [eevee/lexys-labyrinth#9]
On the page https://c.eev.ee/lexys-labyrinth/, the "Just play something" level packs don't do anything when clicked

The web console shows this error:
```
main.js:1788 Uncaught (in promise) TypeError: Cannot read property 'total_score' of null
    at Conductor.load_game (main.js:1788)
    at Conductor.parse_and_load_game (main.js:1921)
    at Conductor.fetch_pack (main.js:1882)
```
Happens in both latest Chrome and Firefox

Are these not meant to be loaded? Do they require some additional user action?

**Comment by eevee** [comment]
_Whoops_, no, that's my bad.  Only happens if you haven't played them yet, which is why I didn't notice!  Should work now.
