### ISSUE TITLE
Can't start a level by touch on an Android tablet

### ISSUE THREAD

**Issue by PixievoltNo1** [eevee/lexys-labyrinth#93]
I'd love to play this on my tablet, but once I load a level pack and am presented with a level, there is no Play button and the game board does not respond to the touchscreen. If I connect a keyboard and start the level that way, the touchscreen works fine until the next level. I'm experiencing this on both Firefox and Samsung Internet (a Chrome-ish browser).

**Comment by PixievoltNo1** [comment]
I've had a look through the code and I can see how it can be done - check in [this touch handler](https://github.com/eevee/lexys-labyrinth/blob/15a8be1c15f7d82536e9c8a21a97047fe49c5e80/js/main.js#L921) if we're waiting and there's no mobile pause menu, and start playing if so, and make [this text](https://github.com/eevee/lexys-labyrinth/blob/15a8be1c15f7d82536e9c8a21a97047fe49c5e80/js/main.js#L1985) change if we're using a touch screen. Determining if there's a mobile pause menu could be done with `getComputedStyle(this.mobile_pause_menu).display === 'none'`, though that's a tad hacky. Want a PR?

**Comment by eevee** [comment]
this is fixed now; i merged #94 but also then ended up just making the overlay clickable/tappable under any circumstances
