### ISSUE TITLE
Add CCLP5? 🥺

### ISSUE THREAD

**Issue by lydell** [eevee/lexys-labyrinth#98]
Thank you for this amazing emulator!

Would you mind adding [CCLP5](https://bitbusters.club/cclp5/) which dropped a couple of weeks ago?

**Comment by eevee** [comment]
It is done

6d6f4f7

**Comment by lydell** [comment]
![yay](https://github.com/eevee/lexys-labyrinth/assets/2142817/61d4357e-a545-4a22-a501-b41d7fbb2896)

Yay! Thank you! 💙
